import type { User, Organization, Bill, BillLineItem, DashboardStats } from "./types"

// Mock current user
export const mockUser: User = {
  id: "user_1",
  email: "demo@billsage.com",
  name: "Sarah Johnson",
  organizationId: "org_1",
  role: "user",
  createdAt: "2024-01-15T10:00:00Z",
}

// Mock organization
export const mockOrganization: Organization = {
  id: "org_1",
  name: "Johnson Family",
  plan: "pro",
  createdAt: "2024-01-15T10:00:00Z",
  billCount: 12,
  totalSavings: 4825.5,
}

// Sample line items for bills
const sampleLineItems1: BillLineItem[] = [
  {
    id: "item_1",
    serviceCode: "99213",
    cptCode: "99213",
    description: "Office visit, established patient, moderate complexity",
    date: "2024-10-15",
    billedAmount: 450.0,
    quantity: 1,
    provider: "Memorial Hospital",
    insurerAllowed: 125.0,
    patientResponsibility: 450.0,
    isOverpriced: true,
    recommendedPrice: 150.0,
    confidence: 92,
    reasoning:
      "The billed amount of $450 for a CPT 99213 office visit significantly exceeds the Medicare rate of $110 and typical commercial rates of $120-180. This charge is approximately 3x higher than fair market value for this service in your region.",
    savings: 300.0,
  },
  {
    id: "item_2",
    serviceCode: "36415",
    cptCode: "36415",
    description: "Venipuncture (blood draw)",
    date: "2024-10-15",
    billedAmount: 125.0,
    quantity: 1,
    provider: "Memorial Hospital",
    insurerAllowed: 12.0,
    patientResponsibility: 125.0,
    isOverpriced: true,
    recommendedPrice: 15.0,
    confidence: 98,
    reasoning:
      "Standard venipuncture typically costs $8-25 nationally. The $125 charge is approximately 8x the fair market rate. This is a common item with well-established pricing benchmarks.",
    savings: 110.0,
  },
  {
    id: "item_3",
    serviceCode: "80053",
    cptCode: "80053",
    description: "Comprehensive metabolic panel",
    date: "2024-10-15",
    billedAmount: 285.0,
    quantity: 1,
    provider: "Memorial Hospital",
    insurerAllowed: 45.0,
    patientResponsibility: 285.0,
    isOverpriced: true,
    recommendedPrice: 50.0,
    confidence: 95,
    reasoning:
      "A comprehensive metabolic panel (CMP) typically costs $30-75 at most facilities. Direct-pay labs offer this for $25-40. The $285 charge is 4-5x typical rates.",
    savings: 235.0,
  },
  {
    id: "item_4",
    serviceCode: "J0290",
    cptCode: null,
    description: "Ampicillin injection, 500mg",
    date: "2024-10-15",
    billedAmount: 45.0,
    quantity: 2,
    provider: "Memorial Hospital",
    insurerAllowed: 8.0,
    patientResponsibility: 90.0,
    isOverpriced: false,
    recommendedPrice: 40.0,
    confidence: 78,
    reasoning:
      "This antibiotic injection pricing is within acceptable range. Hospital markup on medications varies, but this falls within typical bounds for generic injectable medications.",
    savings: 10.0,
  },
]

const sampleLineItems2: BillLineItem[] = [
  {
    id: "item_5",
    serviceCode: "43239",
    cptCode: "43239",
    description: "Upper GI endoscopy with biopsy",
    date: "2024-09-22",
    billedAmount: 4200.0,
    quantity: 1,
    provider: "City Medical Center",
    insurerAllowed: 1200.0,
    patientResponsibility: 4200.0,
    isOverpriced: true,
    recommendedPrice: 1800.0,
    confidence: 88,
    reasoning:
      "Facility fees for upper endoscopy with biopsy typically range from $1,200-2,500. The $4,200 charge exceeds the 90th percentile for this procedure in your region. Consider requesting an itemized bill and negotiating.",
    savings: 2400.0,
  },
  {
    id: "item_6",
    serviceCode: "00740",
    cptCode: "00740",
    description: "Anesthesia for upper GI procedures",
    date: "2024-09-22",
    billedAmount: 1850.0,
    quantity: 1,
    provider: "City Medical Center",
    insurerAllowed: 450.0,
    patientResponsibility: 1850.0,
    isOverpriced: true,
    recommendedPrice: 600.0,
    confidence: 85,
    reasoning:
      "Anesthesia for a 30-45 minute upper GI procedure typically costs $400-800. This charge appears to use inflated time units or facility multipliers.",
    savings: 1250.0,
  },
  {
    id: "item_7",
    serviceCode: "88305",
    cptCode: "88305",
    description: "Surgical pathology, biopsy",
    date: "2024-09-22",
    billedAmount: 380.0,
    quantity: 2,
    provider: "City Medical Center",
    insurerAllowed: 120.0,
    patientResponsibility: 760.0,
    isOverpriced: false,
    recommendedPrice: 350.0,
    confidence: 72,
    reasoning:
      "Pathology fees for biopsy specimens vary widely. While on the higher end, this pricing is within the acceptable range for hospital-based pathology services.",
    savings: 60.0,
  },
]

const sampleLineItems3: BillLineItem[] = [
  {
    id: "item_8",
    serviceCode: "99284",
    cptCode: "99284",
    description: "Emergency department visit, high severity",
    date: "2024-11-05",
    billedAmount: 2800.0,
    quantity: 1,
    provider: "Regional Medical ER",
    insurerAllowed: 650.0,
    patientResponsibility: 2800.0,
    isOverpriced: true,
    recommendedPrice: 850.0,
    confidence: 90,
    reasoning:
      "Level 4 ED visits typically cost $500-1,200 at most facilities. The $2,800 facility fee is well above the 95th percentile for this service level.",
    savings: 1950.0,
  },
  {
    id: "item_9",
    serviceCode: "71046",
    cptCode: "71046",
    description: "Chest X-ray, 2 views",
    date: "2024-11-05",
    billedAmount: 650.0,
    quantity: 1,
    provider: "Regional Medical ER",
    insurerAllowed: 85.0,
    patientResponsibility: 650.0,
    isOverpriced: true,
    recommendedPrice: 120.0,
    confidence: 96,
    reasoning:
      "A 2-view chest X-ray has well-established pricing of $50-150. Imaging centers offer this for $40-80. The $650 charge is 5-6x fair market value.",
    savings: 530.0,
  },
]

// Mock bills
export const mockBills: Bill[] = [
  {
    id: "bill_1",
    userId: "user_1",
    organizationId: "org_1",
    fileName: "memorial_hospital_oct_2024.pdf",
    fileType: "pdf",
    uploadedAt: "2024-10-20T14:30:00Z",
    status: "analyzed",
    provider: "Memorial Hospital",
    totalBilled: 950.0,
    totalRecommended: 295.0,
    totalSavings: 655.0,
    lineItems: sampleLineItems1,
  },
  {
    id: "bill_2",
    userId: "user_1",
    organizationId: "org_1",
    fileName: "endoscopy_sep_2024.pdf",
    fileType: "pdf",
    uploadedAt: "2024-09-28T09:15:00Z",
    status: "analyzed",
    provider: "City Medical Center",
    totalBilled: 6810.0,
    totalRecommended: 3100.0,
    totalSavings: 3710.0,
    lineItems: sampleLineItems2,
  },
  {
    id: "bill_3",
    userId: "user_1",
    organizationId: "org_1",
    fileName: "er_visit_nov_2024.pdf",
    fileType: "pdf",
    uploadedAt: "2024-11-10T16:45:00Z",
    status: "analyzed",
    provider: "Regional Medical ER",
    totalBilled: 3450.0,
    totalRecommended: 970.0,
    totalSavings: 2480.0,
    lineItems: sampleLineItems3,
  },
  {
    id: "bill_4",
    userId: "user_1",
    organizationId: "org_1",
    fileName: "dental_checkup.csv",
    fileType: "csv",
    uploadedAt: "2024-11-18T11:20:00Z",
    status: "processing",
    provider: "Bright Smile Dental",
    totalBilled: 425.0,
    totalRecommended: 0,
    totalSavings: 0,
    lineItems: [],
  },
]

// Mock dashboard stats
export const mockDashboardStats: DashboardStats = {
  totalBills: 12,
  totalAnalyzed: 11,
  totalSavings: 8245.5,
  averageSavingsPerBill: 749.59,
  recentBills: mockBills.slice(0, 3),
  monthlySavings: [
    { month: "Jun", savings: 420 },
    { month: "Jul", savings: 890 },
    { month: "Aug", savings: 1250 },
    { month: "Sep", savings: 3710 },
    { month: "Oct", savings: 655 },
    { month: "Nov", savings: 2480 },
  ],
}

// Mock organizations for admin
export const mockOrganizations: Organization[] = [
  mockOrganization,
  {
    id: "org_2",
    name: "Smith Healthcare LLC",
    plan: "enterprise",
    createdAt: "2024-02-20T08:00:00Z",
    billCount: 45,
    totalSavings: 18420.0,
  },
  {
    id: "org_3",
    name: "Williams Family",
    plan: "free",
    createdAt: "2024-03-10T15:30:00Z",
    billCount: 3,
    totalSavings: 890.0,
  },
  {
    id: "org_4",
    name: "MedCare Consulting",
    plan: "pro",
    createdAt: "2024-04-05T12:00:00Z",
    billCount: 28,
    totalSavings: 12350.0,
  },
]
